### ISSUE TITLE
Enable auto-publishing to NPM for `@bigtest/agent` and friends

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#127]
We're ready to start relying on `@bigtest/*` packages out there in the great big world, so we need to synchronize to NPM with a pull to master.

Right now, we want to ignore all of the legacy packages that have been brought in from the old repo. This includes:

* `@bigtest/cli`
* `@bigtest/convergence`
* `@bigtest/interactor`

Any packages that we create (and we will be adding many including `@bigtest/suite`, `@bigtest/server`, etc.... in the future) should automatically get picked up in the flow without having to take extra steps.

**Comment by minkimcello** [comment]
So I was looking over `synchronize-with-npm` (release action) and it looks like it has not yet been updated to support monorepos. I was holding off on doing more work on these actions until after the Javascript refactor. I could copy over the release action from the `resideo/actions` repository and undo some of the resideo-specific options (like versioning and hard-coded authentication for github package repository). Should we do that since we need a release workflow up and running for bigtest?

**Comment by cowboyd** [comment]
I don't know how my reply got lost in this, but yes, we need this since we have `@bigtest/agent`, `@bigtest/project` and `@bigtest/cli` all needing to be published.
