### ISSUE TITLE
Type-check test bundle

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#280]
We use parcel to bundle the manifest which means that if you're writing your tests in TypeScript, everything will "Just Work" ™️.  But parcel uses babel typescript to just strip the type annotations away from your javascript code and not actually type-check. This means that invalid code can get through and try to be required by the bundle.

We need to typecheck the test code before hand and communicate the error to the user rather than crash the server which is what happens now.

**Comment by jnicklas** [comment]
This issue is really such a bummer. I still can't understand how the parcel folks feel that this behaviour is good :(. I almost feel like we *shouldn't* do anything about this though. This is really parcel's problem to fix, and I don't love doing something like invoking tsc if we see any TypeScript files. It feels to me like everything we do in bigtest to fix this problem is going to be a really nasty hack which might break in unexpected ways.

**Comment by pittst3r** [comment]
We are now using rollup to build the test files. However, we are still using babel to handle TS, which does not typecheck. That said, I think it is a better DX to have typechecking and building as separate steps because:

- TSC is slow
- Sometimes trivial type errors get in my way when I'm moving quickly and I want to defer fixing the type error
- We can introduce the idea of Validators which is a pluggable way to handle linting and type checking

Validators have the following attributes:

- There can be one or more of them
- They are pluggable
- They are kicked off when the test files change
- They only validate test files
- They do not block the test run following the rebuild, even if they fail

Questions about Validators:

- Do they use config files in the root of the project or the test directory?
- How should they report results? After the test run?

**Comment by cowboyd** [comment]
> Do they use config files in the root of the project or the test directory?

For all intents and purposes, I think we should treat the test bundle as its own self-contained javascript module, which means that it should not automatically pull in things from the ambient environment. This will let us embed a BigTest suite into _any_ project no matter what it looks like. If we don't, we're going to be playing an endless game of whack-a-mole with the fractal complexity of potential JavaScript configuration.

I like the validator pattern you've laid out because it should also allow us to store bundle validation state in the `Atom` so that when building stateful ui's and inpsectors, this information is readily available. A good heuristic when designing these APIs could be "what information do I need to collect to build a stateful UI on top of this"

**Comment by jnicklas** [comment]
So I think I have a way forward for this:

I've experimented a lot with the `@rollup/plugin-typescript` plugin and how it works, and I think we can make it work and this is how I think we should proceed on integrating it:

1. We add a config option to `bigtest.json` to specify the path for a tsconfig file.
1. This file will have `extends: "./tsconfig.json"` if the project has a regular tsconfig file.
1. It will override certain settings that are advantageous to override
1. The plugin configuration in `@bigtest/bundler` will make further changes which are necessary, most notably `declaration: false`.
1. Our `init` script will ask the user whether they want to create this file
1. If they choose not to create a file, the config option in `bigtest.json` won't be set and the default `tsconfig` will be used if it exists.

I think this is the best path forward.

Using the "normal" tsconfig file is problematic for the following reasons:

1. The list of files specified in `includes` should ideally only include the test files
1. Various compiler options might be different for the tests versus the tsconfig for the app
1. Especially we might want to default to `noEmitOnError: true`

Specifying the typescript settings in `bigtest.json` is also problematic:

1. It does not integrate with the wider ecosystem
1. When using the rollup plugin, some options (notable include!) actually take precedent from the tsconfig over the plugin configuration. I'm not sure if this is a bug, but it definitely leads to some pretty confusing behaviour
1. We'll need to specify a separate glob for typescript files (it must not include plain `.js` files), and doing this in our config feels awkward to me.
