### ISSUE TITLE
Make assertions convergent over time

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#291]
The runner [only runs an assertion once][1], but it may be possible that effects of the actions in a step have yet to be fully realized in a form that will make the assertion pass. We've done this in the past with `@bigtest/convergence` to happy effect

![picture of many assertions that eventually pass once an effect has been realized in application state](https://raw.githubusercontent.com/bigtestjs/bigtest/master/packages/convergence/images/convergent-assertion.png)

[1]: https://github.com/thefrontside/bigtest/blob/master/packages/agent/app/create-harness.ts#L87

**Comment by jnicklas** [comment]
Personally, I'd kind of like to hold off on making assertions convergent until we have a better understanding of the interactor API. My gut feeling is still that assertions should be async functions. My thinking is that adding convergence to assertions will make the interactor API more inconsistent, and ultimately confusing to use. I know I haven't done a good job of articulating why I think this is the case, so I'll try to explain.

The main reason for this is the need for "anchoring" steps through assertions. Basically this is like adding debug asserts to code to ensure that you are in the right place. An easy to understand example would be a paginated list. Imagine you want to navigate to the *third* page of a paginated list. You'd have to click "next" twice:

``` javascript
// I'm on the first page
await Link("next").click()
// Am I on the second page?
await Link("next").click()
// Wait, where am I now?
```

The problem here is that you cannot know whether you have actually transitioned to the second page before you click the "Next" link the second time. So you might end up hitting "Next" twice on the first page, leaving you on the second page instead. So you'd want to anchor this test by adding an assertion in between:

``` javascript
await Link("next").click()
await Headline("Page 2").exists()
await Link("next").click()
```

There is no longer any ambiguity in this.

> **Sidenote:** A mistake which I think most frameworks in this space make is they fail to realize that the first case is inherently ambiguous and *cannot* definitively be resolved. They try to guess what the user meant and often end up getting it wrong. Writing a test like this is simply a mistake, and we should teach people to do the right thing, rather than making bad guesses.

But now we have a way of asserting on things in steps, which is asynchronous and in some way "contained" in the interactor API. It feels awkward to me to then have a *different* way of asserting in actual assertions. Additionally, making non-convergent access to properties on an interactor too easy, means that it's liable to be misunderstood or misused when it *does* need to be convergent on its own. Imagine if we have two different ways of verifying the `href` of a link:

``` javascript
// non-convergent
Link('Foobar').href === 'http://example.com';
// convergent
await Link('Foobar').hasProperty('href', 'http://example.com');
```

IMO it's harder to explain the difference between these two, rather than just always using the latter.

Also I'm a bit worried that we will need a deeper integration between interactors and the framework, but I'm not sure whether this is actually true.

**Comment by jnicklas** [comment]
With #309 merged, it seems that we've settled on convergence being a property of interactors and not assertions.
