### ISSUE TITLE
Add built in interactors

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#379]
Once #359 is merged, we will want to add a suite of built in interactors to ship out of the box.

I've compiled a list of interactors here which will we can fill out as we come up with more ideas. Potentially useful filters are in parentheses.

Almost all interactors should have some visibility filter.

- [x] Link (href,target)

### Form elements

All form elements should have an `enabled` filter.

- [x] Select
- [x] TextArea
- [x] Checkbox (checked)
- [x] Button *should allow `<button>`, `<input type="submit">`, `<input type="button">`, `<input type="reset">` and `<input type="image">`*
- [x] TextField (value) *should use `<input type="text">` but also `<input>` without a type*
- [x] ColorField (value) 
- [x] DateField (value) 
- [x] DateTimeField (value) *should use `<input type="datetime-local">` since `datetime` is obsolete*
- [x] EmailField (value) 
- [ ] FileField (accept,capture,multiple) *how do we upload files?! this one is tricky*
- [x] HiddenField *not really normally available to users, so we maybe we should omit this?*
- [x] MonthField (value)
- [x] NumberField (value)
- [x] PasswordField (value)
- [x] RadioField (value,checked)
- [ ] RangeField
- [x] SearchField
- [x] TelephoneField
- [x] TimeField
- [x] UrlField
- [x] WeekField

## Acceptance Criteria

Must work and be tested with Popular Frameworks, including
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Svelte
- [ ] Ember

**Comment by jnicklas** [comment]
There are a lot of fields that are "text-like", should there be some common interactor for all of these?

Namely text areas and also input without type and with type `text`, `number`, `email`, `password`, `search`, `tel` and `url`.

**Comment by cowboyd** [comment]
Also, all form elements should have a `focus` action.

**Comment by jnicklas** [comment]
So, one thing I just ran into as I was looking into building a `Link` interactor: ARIA roles.

Maybe this is not something we should worry about right now, but I thought it'd be worth mentioning. A link with `role="button"` should be treated as a button, not as a link, so should the `Link` interactor find such a link? Should the `Button` interactor? I think it would probably be good to respect ARIA attributes, but it does complicate things.

**Comment by jnicklas** [comment]
Another wrinkle I ran into:

Most interactors built for HTML elements (as opposed to say, SVG) have a few things in common. We want to be able to filter by `id`, be able to click basically anything, filter by visibility, and so on. It would be nice to abstract this away, so we can reuse it for all of them. My initial thinking was to add a `createHtmlInteractor` which wraps `createInteractor` and simply adds the relevant defaults. But this turns out to be.... not easy.

In plain JS this is a no-brainer, but the tricky part is getting TypeScript to get the types right.

I attempted to do something like this, but TypeScript does not understand this, unfortunately:

``` typescript
import { createInteractor } from './create-interactor';
import { InteractorSpecification, InteractorType } from './specification';

export interface WithHTMLExtensions<E extends HTMLElement, S extends InteractorSpecification<E>> extends InteractorSpecification<E> {
  actions?: {
  } & S['actions'];
  locators?: {
    byId: (element: E) => string
  } & S['locators'];
  filters?: {
  } & S['filters'];
}

export function createHtmlInteractor<E extends HTMLElement>(interactorName: string) {
  let builder = createInteractor<E>(interactorName);
  return function<S extends InteractorSpecification<E>>(specification: S): InteractorType<E, WithHTMLExtensions<E, S>> {
    return builder({
      selector: specification.selector,
      defaultLocator: specification.defaultLocator,
      locators: {
        byId: (element) => element.id,
        ...specification.locators
      },
      actions: {
        ...specification.actions
      },
      filters: {
        ...specification.filters
      }
    });
  }
}
```

**Comment by dagda1** [comment]
@jnicklas this brings me back to what I said previously.

I don't think the current way of having the `InteratorSpecification` as a generic type constraint offers great type safety.

also all the fields of `InteractorSpecification` are optional

My first thoughts are that I think the argument should be that type and not specified by the type constraint.

```typescript
return function(specification: S extends InteractorSpecification<E>): 
```

Actions, filters and locators can somehow be type constraints

**Comment by jnicklas** [comment]
Another question that popped into my mind:

There are multiple HTML tags which represent a "button" so it makes sense for the button interactor to encompass all of these. For the user, there is not practical difference between them, so they shouldn't have to care whether the underlying tag is `<button>` or `<input type="button">`.

However, what is a text field? From the users perspective, a text field is probably "anything I can enter text into". Does this include text areas? Does it include fields of `<input type="email">`? How about `<input type="password">`? Should there be a separate `PasswordField` interactor?

Basically which of these should be covered by which interactors:

```
- textarea
- input:not([type])
- input[type="text"]
- input[type="email"]
- input[type="number"]
- input[type="password"]
- input[type="search"]
- input[type="tel"]
- input[type="url"]
```

Then there are also the time based input fields, which mostly also render as text fields, especially on browsers that don't support them (e.g. FF does not support month/week) but these are actually even more problematic, since straight-up entering text into them sometimes won't provide the desired result.

```
- input[type="date"]
- input[type="datetime"]
- input[type="datetime-local"]
- input[type="month"]
- input[type="time"]
- input[type="week"]
```

**Comment by cowboyd** [comment]
@jnicklas In this case, it might be helpful if we think of interactors via the lens of algebraic types. In other words, the type is defined by the _operations_ that are valid over all instances of that type. In our case, actions constitute the operations. So, if the actions that are valid on a text area have the same implementation as, then it seems like it should be the same interactor. 

However, this breaks down when we view them through the lens of filtering since different HTML tags could have different data structures. So while the actions might be uniform, acquiring references won't be. For example, in a `textarea` the content is contained inside the node's children, where as an input has it as an attribute. The fundamental tension at play then it seems is that all of these inputs share a common set of operations, but their data is organized differently.

 One option would be to separate construction from type and essentially make each interactor class a union of specific types?  

One way would be to just use a discriminated union.

```ts
type Text = TextInput | EmailInput | NumberInput | Password Input | TextArea | TelephoneInput | URLInput;
//....
let text: Text = TextArea('notes');
text.type('Remember to buy Milk');
```

That's pretty a pretty big DIY project, which we could do, but might be a pretty big ask for folks writing their own interactor libraries. It also completely punts on the problem of sharing implementations.

Another option is to really formally separate the boundaries of construction and operation where you have an Action class that takes an element and performs operations, and a Finder class that implements your location and filtering, and you combine them to make an interactor:

```ts
import { Text } from './actions/text';

export const TextArea = Text(TextAreaFilters);
export const Input = Text(InputFilters);
```

However we organize the code though, I think we should break down these lists into discrete operations, and see which of these elements share which operations so that we can actually see where the overlap is, and perhaps more importantly the non-overlap is. Once we know which buckets they go in, we can decide how to share interface and implementation.

**Comment by cowboyd** [comment]
I mean this is essentially what we're doing already with the `actions` and `filters` property which decouples the two, so I'm not really adding anything new other than "let's comprehensively document the operations and see which elements we should pair with which operations"

**Comment by cowboyd** [comment]
@jnicklas I ran into to a signin form in the [realworld app](https://realworld.io) which uses `<input type=email/>` which feels like it should work with the `TextField` interactor.

![signin form with fields indistinguishable from a normal text field](https://user-images.githubusercontent.com/4205/95403260-4f846680-08d7-11eb-879a-8956302ed3e3.png)

Based on the way it looks, and how you interact with it, including the types of events it receives, I think it's indistinguishable from a text field, so my vote is that in this case, it should match the TextField interactor.
