### ISSUE TITLE
Ensure no two test have the same path

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#506]
We encountered the following test files:

// companies.test.ts
```ts
import { test } from '@bigtest/suite';

export test('Admin UI')
  .step()
```

And also in

// accounts.test.ts
```ts
import { test } from '@bigtest/suite';

export test('Admin UI')
  .step()
```

As a result, both of these tests had a path of `['All Tests', 'Admin UI']` so the steps associated with these tests ran twice. In our case, Mirage was installed twice. We should invalidate a bundle that has duplicate paths of tests.

related:  #294

**Comment by jnicklas** [comment]
I've been thinking about this issue a bit and I wanted to point a flaw in our thinking here, and possible alternatives to how we might think about it:

The following is a pretty realistic test scenario:

``` typescript
test("go to third page")
  .step(Link("Next").click())
  .step(Heading("Page 2").exists())
  .step(Link("Next").click())
```

While there is no duplication among *tests* the two *steps* that have click the `Next` link have the same path. We currently assume this cannot happen, which is incorrect. IMO it should be perfectly fine to have duplicate descriptions among steps.

So why do tests need to be unique, but steps don't? Simply because step paths are only relevant in the context of one particular test run, whereas test paths should be stable across test runs. It would be nice to be able to re-run a particular test based on its path. But running an individual step doesn't make sense. Steps are only ever run as part of an entire lane.

Two questions:

1) How about assertions? Should assertions be unique? I can't see a reason for having multiple assertions with the same name, and it would be quite convenient to be able to re-run them by path, even if for example the order changes or the steps before it change, or whatever.

2) How should we express the path to a step? Currently path are arrays, this has the advantage of not having to parse the path, and not leaving any holes where using some special character in a description could cause bugs. Should we just use an array index for steps, like this:

``` javascript
["All tests", "go to third page", 0]
["All tests", "go to third page", 2]
```

**Comment by cowboyd** [comment]
For (1), I agree with your initial inclination that we should disallow duplicate assertions. Any assertion that changed the outcome of a test by duplicating or not duplicating would, by definition be an invalid assertion.

For (2) An array does make sense since steps are implicity ordered. That's kinda their whole deal. And in fact, on the _runner_ side of things, we only use the test path to run steps, and not the step path https://github.com/thefrontside/bigtest/blob/fillin-react/packages/agent/app/run-lane.ts#L67

It would only be fore the _reporting_ end of things that we need to be able to disambiguate steps and we're currently not. An alternative that might make debugging more friendly would be to have the path include both the order and the description. E.g.

```json
["All tests", "go to third page", "0:click the next link"]
["All tests", "go to third page", "1:heading 'Page 2' exists "],
["All tests", "go to third page", "2:click the next link"]
```


<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 50 million people use GitHub to discover, fork, and contribute to over 100 million projects.</div></blockquote>
