### ISSUE TITLE
Check global page properties via Page/App interactor

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/bigtest#582]
Tracking this here after the discussion in discourse yesterday.

There are some properties of a page which we might want to test but which are not directly related to any element on the page, some examples:

- page title
- url (can be further broken down into its various components)
- text (regardless of location)

One possibility is to make the app interactor a proper interactor and implement these as filters:

``` typescript
await App.has({ title: "blah" });
```

A more appropriate name in this case might be `Page`, rather than `App`. Maybe that's where we could move `visit` as well, in that case.

``` typescript
await Page.has({ title: "blah" });
await Page.visit("/foo");
```

**Comment by cowboyd** [comment]
I think I prefer `Page` since it lines up more with where HTML specific than `App`. Ideally, we'd use `Window` but that's already taken by the `window` object constructor:

```ts
await Page.has({ location: '/foo', title: "blah" });
```

That feels pretty great. Does our interactor syntax currently support non-element interactors? I guess we could make `selector` a function or a string?

**Comment by jnicklas** [comment]
I think we should probably make this a completely different class entirely.
