### ISSUE TITLE
Chromedriver timeout

### ISSUE THREAD

**Issue by minkimcello** [thefrontside/bigtest#669]
There was an issue with chromedriver not downloading/unzipping properly so our workaround was to include this in our Github Actions workflow:
```
run: echo "chromedriver_filepath=$CHROMEWEBDRIVER" >> .npmrc
```

We hoped this would solve our occasional timeout issue but the problem still occurs.

This is the error output:
<img width="1151" alt="Screen Shot 2020-11-06 at 1 25 59 PM" src="https://user-images.githubusercontent.com/29791650/98403397-e65b5480-2036-11eb-88fd-bd9ecd6e6f63.png">

When it happens locally I just need to run the command again and it'll start up. And in CI as well, if you `re-run` the workflow it'll solve itself but I think we should at least have an explanation as to why this is still happening even when we include a local filepath to chromedriver.

**Comment by cowboyd** [comment]
I think we may just have to bounce the chrome driver process.... maybe say give it 2s to come up, and restart it 5 times or something like that.

**Comment by cowboyd** [comment]
This looks like a recurring failure in the windows cli tests https://github.com/thefrontside/bigtest/pull/659/checks?check_run_id=1460287789#step:7:197

<blockquote><img src="https://avatars3.githubusercontent.com/u/134?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/thefrontside/bigtest/pull/659">Start adding docs via typedoc by jnicklas · Pull Request #659 · thefrontside/bigtest</a></strong></div><div>This is a first stab at adding docs via TypeDoc.
Unfortunately this uses a frozen in time, outdated fork of TypeDoc, found here TypeStrong/typedoc#1184, because the output generated just isn&#39;t ...</div></blockquote>

**Comment by jbolda** [comment]
@cowboyd It might be the same underlying issue, but @minkimcello's case fails due to timeout in `webdriver` where the test that you linked seems to fail to the timeout set in the bigtest cli test (which is also the same as the default when run in CI) .
