### ISSUE TITLE
Improve error message for createInteractor

### ISSUE THREAD

**Issue by jenweber** [thefrontside/bigtest#820]
If you don't pass a string to `createInteractor`, you get the following message:

> ERROR Cannot read property 'length' of undefined

It would be better for this error to be caught and have a message like:

> "Please provide a description for your interactor, such as `createInteractor('username input')`

**Comment by minkimcello** [comment]
<details>
<summary>convoluted mumbo jumbo</summary>
<br>
So I've looked into this and it seems we only need to worry about javascript tests because in typescript it'll tell you what's wrong before it tries to instantiate the interactors:
<br>
<img src="https://user-images.githubusercontent.com/29791650/118257538-bf199000-b47c-11eb-9aa7-8843440edba8.png"/>
<img src="https://user-images.githubusercontent.com/29791650/118257548-c0e35380-b47c-11eb-832c-69723ee1edcf.png"/>

So with the introduction of the `extend()` API, we now have to cover two different scenarios (if we want to display the error message you suggested). But first I installed the sample app to investigate exactly what the current behaviour is.

I found that for both `createInteractor()` and `extend()`, it will not throw an error as long as the tests pass (they both funnel through the same constructor so it's not a surprise that they both behave the same way). Not passing in a name only becomes an issue when a test fails. In the bigtest runner, we get a `ERROR h is undefined` and for both jest and cypress, we get `TypeError: Cannot read property 'length' of undefined`.
<hr>
</details>

My initial thought was to throw an error inside the constructor so that when an interactor is created (or extended), it'll display an error message to remind users to pass in a string. But, I don't think this would be the best approach because the stack trace doesn't tell us which interactor it is having issues with.

Here's what it looks like when we throw an error (`nooo`) inside the constructor:
![Screen Shot 2021-05-14 at 6 48 29 AM](https://user-images.githubusercontent.com/29791650/118260566-7e237a80-b480-11eb-9c9f-cd732f285f51.png)

And here's what it looks like currently with the bigtest runner:
![Screen Shot 2021-05-14 at 6 48 10 AM](https://user-images.githubusercontent.com/29791650/118260608-867bb580-b480-11eb-8c87-3e5a1ae9733a.png)

And in jest:
![Screen Shot 2021-05-14 at 7 02 22 AM](https://user-images.githubusercontent.com/29791650/118262051-5af9ca80-b482-11eb-897f-f96bfc2f9786.png)

In a way, it's easier to track down which interactor is missing a name as it is currently. I could go into the bigtest runner and display a warning each time an interactor's name is "undefined" but then we'd have to find a solution for jest and cypress separately. Thoughts?

**Comment by cowboyd** [comment]
@minkimcello @jenweber There are a couple of options:

1. what if we just made a default `anonymous interactor` and it is not an error
2. we defer the error from when you construct the interactor until you use the interactor
3. we defer and make it a warning.

Hard to say which is best.

**Comment by minkimcello** [comment]
> @minkimcello @jenweber There are a couple of options:
> 
>     1. what if we just made a default `anonymous interactor` and it is not an error
> 
>     2. we defer the error from when you construct the interactor until you use the interactor
> 
>     3. we defer and make it a warning.
> 
> 
> Hard to say which is best.

Oh I spoke too soon earlier. I realized I can throw in the `console.warn` inside `findMatches()` to get the behaviour we're looking for.

I don't think we should have an anonymous interactor. That just creates one more thing we need to explain.

And I think we should throw a hard error to force people to use interactors properly. It also formats more nicely.

As a console warn:
![Screen Shot 2021-05-18 at 7 40 24 AM](https://user-images.githubusercontent.com/29791650/118645043-6dd70c80-b7ac-11eb-92e5-dbb316a43823.png)

When we throw an error:
![Screen Shot 2021-05-18 at 7 41 02 AM](https://user-images.githubusercontent.com/29791650/118645074-7af3fb80-b7ac-11eb-9e03-b001f4842db8.png)

**Comment by cowboyd** [comment]
Perfect! 

So sounds like the options are:

1. whiny anonymous interactor
2. fail if no name

I kinda lean towards the (2) but don't feel strongly either way.
