### ISSUE TITLE
Importing bigtest/cypress breaks Cypress' `.should()`

### ISSUE THREAD

**Issue by taras** [thefrontside/bigtest#962]
@axelhunn found this in https://github.com/folio-org/stripes-testing/pull/116/files#r679459664

Expected behavior: there should be no adverse impact on Cypress by importing `@bigtest/cypress` package

**Comment by minkimcello** [comment]
~~This might be because we're still on 7.2.0 and it looks like there was a bug around `.should` that was addressed in 7.5.0?~~

https://docs.cypress.io/guides/references/changelog#7-5-0

<blockquote><img src="https://docs.cypress.io/img/real-world-app.png" width="48" align="right"><div><img src="/img/favicon.ico" height="14"> Cypress Documentation</div><div><strong><a href="https://docs.cypress.io/guides/references/changelog">Changelog | Cypress Documentation</a></strong></div><div>Cypress Documentation</div></blockquote>

**Comment by taras** [comment]
@minkimcello can we bump up and make a release?

**Comment by minkimcello** [comment]
@taras i'm on it now

**Comment by cowboyd** [comment]
It looks like a case of cypress not fully using ES modules internally. I created this upstream issue https://github.com/cypress-io/cypress/issues/17564
